# Generated by Django 5.1 on 2024-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_result_pass_fail_certificate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
