# Generated by Django 5.1 on 2024-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_certificate_certificate_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Directorate",
            field=models.CharField(default="Kanpur", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="Year",
            field=models.IntegerField(default=24, null=True),
        ),
    ]
