# Generated by Django 5.1.1 on 2024-09-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_student_directorate_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
            ],
        ),
    ]
