# Generated by Django 5.1.1 on 2024-09-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name_hindi',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name_hindi',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
