# Generated by Django 5.1 on 2024-10-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_student_fathers_name_hindi_student_name_hindi"),
    ]

    operations = [
        migrations.AddField(
            model_name="clerk",
            name="certificate_no_current",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name="clerk",
            name="certificate_no_end",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name="clerk",
            name="certificate_no_start",
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
